# Generated by Django 5.1 on 2024-08-17 16:09

from django.db import migrations, models

class Migration(migrations.Migration):

    # This migration is the initial migration for the 'myapp' app
    initial = True

    dependencies = [
        # Specify any dependencies this migration has on other migrations here
        # For example: ('app_name', 'migration_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'item',
            },
        ),
    ]
