# Generated by Django 5.1 on 2024-08-17 16:32
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='new_field',
            field=models.CharField(max_length=255, default='default value'),
        ),
    ]
