# Generated by Django 5.1 on 2024-08-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240817_1632'),
    ]

    operations = [
    ]
