# Generated by Django 5.1 on 2024-08-17 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20240817_2109'),
    ]

    operations = [
    ]
